### ISSUE TITLE
End portal creation sound is very loud

### ISSUE THREAD

**Issue by anoomolu** [gniftygnome/obtainable-end#1]
Hiya, just want to preface by saying THANK YOU for making this mod, it's exactly what I've been looking for!

Been playing around with it in Creative and found that the global sound made when completing the portal frame is ear-piercingly loud, disproportionately so when compared to most other sounds in the game. I'd like to request either a config to disable the sound, or reduce the default volume of the sound.

**Comment by gniftygnome** [comment]
I wondered if I'd get a request to disable.  I don't play with headphones and my laptop's speakers are pretty weak.  I'll see if I can figure out how to scale it to be similar to the completion sound volume.

**Comment by gniftygnome** [comment]
I poked around a bunch and I'm pretty sure vanilla's portal activation sound is louder than my frame completion sound.  I guess you probably disable the portal activation sound somehow?

Anyway, given that fact I'll probably eventually tackle this by adding configuration rather than by nerfing the volume.  It is intended to be an important notification for other players, much like the other global sounds.
